### ISSUE TITLE
Double check that weights load correctly after checkpoint

### ISSUE THREAD

**Issue by alecokas** [deepmagd/shenaniGAN#54]

**Comment by alecokas** [comment]
Seems to be good. Tested by generating using the same noise but with a loaded and just trained model. Everything up to the 3rd decimal in the tf.tensor looks accurate, after that there is variation.

**Comment by Devin-Taylor** [comment]
Can we close this?

**Comment by alecokas** [comment]
I think so - if we see weird things happening with the metrics we can relook at it
